= WRHS Website generator
Rocky Allen, 
2018-09-27
:jbake-type: page
:jbake-status: draft

// tag::body[]

== Introduction 

The purpose of this project is to automate generation of the WRHS website as much as possible, particularly the Trading Post stock listing.
In general, you should never have to edit html or Java code directly.
Another goal is to make it cross-browser and server-agnostic. 
To this end, I avoid JS, CMS, php etc. 
I do use some CSS but it should be usable without (as yet untested).

It is a NetBeans 8.2 project for convenience, but it can be built from the command line without NetBeans.

It builds on Ubuntu with Java 7 or higher.
Other new-ish linux systems should work.

Internally it uses Java, JBake, Apache Ant, and Asciidoctor.

TODO: Remove JBake. 
It is a large dependency and I am only using a tiny bit of it which can be replaced by AsciidoctorJ. 
I think.

== Installation

* Install Java (sudo apt-get install java)

* Install Ant (sudo apt-get install ant)

* Install Git (only required to update the source) (sudo apt-get install git)

* Install JBake (download and expand JBake.zip)

* Extract from Github and copy or expand the entire wrhs folder next to the JBake folder.
(You can put it elsewhere, but you will then have to edit the JBake path in build.xml.)

=== Build

* Open a command window and change directory to wrhs/.
Type:
+
ant build

[[sect-preview]]
== Preview

* Start a local web server:
+
To use JBake, open a command window and change directory to wrhs/.
Type:
+
ant preview
+
Or if you have python installed, open a command window and change directory to wrhs/output/.
Type:
+
python -m SimpleHTTPServer 8080

* Open a browser and point it to:
+
localhost:8080
+
The website will appear served  directly from the output folder.

[[sect-upload]]
== Upload to the public server

* Open a command window and change directory to wrhs/.
Type
+
ant clean build deploy
+
You will be prompted for the username and password.

== Update the stock list

* Download the 2 CSV files from EPOS, and put them in folder wrhs/tradingpost/, overwriting the current ones.

* Open a command window and change directory to wrhs/.
Type
+
ant

* Watch the screen for any errors. 
Particularly look for any type of Exception.

** The most common cause of *FileNotFoundException* is a missing file. 
Did you accidentally delete one or rename it?

** The most common cause of *IOException* is a file is open in another application such as PDF or Excel. 
Close them.

** The most common cause of *DataException* is new data in the product file. 
To add a new category, see <<addcategory>>.

[[addproduct]]
== Add a product in an existing category

Generally new products in existing categories just appear, but you probably want to give it a specific thumbnail.

The file type can be either .png or .jpg.

The file size should be less than 20K (5K is better)

The file name part can either be *exactly* as the same as the "ProductID" field in the product file, or it can be based on the the "Product Name".
To determine the required file name from the product name:

. Replace all non 0-9 or a-z or A-Z with "_".

. Collapse any sequences of "\_" with a single "_".

. Remove leading and trailing "_".

For example if the Product ID is 10056, you can name the file 10056.png or 10056.jpg.
Alternatively, if the Product Name is "Weed & feed, 3 litre (bottle)", the file name can be "Weed_and_feed_3_litre_bottle.png" or "Weed_and_feed_3_litre_bottle.jpg".

Add the photo to 

wrhs/assets/images/{category}/

where {category} is the name of the category *exactly* as it appears in the product file.

Preview the website to make sure that the image appears correctly (<<sect-preview>>).

[[addcategory]]
== Add a category, or re-organise categories

The program uses a category file to organise the categories in the product file into web pages.
All categories listed in the product file must have a matching entry in the category file, or they will cause an error when you build the website.

* Build the website.

* Note the new category from the error message.

* Open wrhs/tradingpost/categorymapping.csv using Excel, Calc, or a text editor.

* Add a row for the new category (__Please keep this file in alphabetic order__).

* Type the page that you want to show the product into the "mapping" column next to the category name.
You can use a new name which will result in a new page, or you can use an existing name so that the item is added to that page.
If you don't want a category to appear on any page, leave its mapping blank.

* Add a new folder 
+
wrhs/assets/images/{category}/
+
where {category} is the name of the category exactly as it appears in the "Category" column.

* Create an image CATEGORY.png in the folder.
This will be used as a thumbnail for that page (one day).

== Add a meeting document

* Copy the file to wrhs/assets/meetings/.

* Add a new row to the table in wrhs/content/society/meetings.adoc following the existing examples.

* Preview the website (<<sect-preview>>).

* Make sure that your new documents are listed.

* Click each document link to make sure it works.

* Upload the website (<<sect-upload>>).

[[add-newsletter]]
== Add a newsletter in the current year (YYYY)

* Create a thumbnail for it (png, width 212 pixels, height 300 pixels).

* Make sure that the file names are like yyyy-mm.pdf and yyyy-mm.png.

* Put the thumbnail and the pdf file in wrhs/assets/newsletters/YYYY. 

== Add a newsletter for a new year

The website is prepared up to 2020.
To make future years visible, uncomment them in file templates/menu.ftl, ie change 

[xml]
--
  <!-- <li><a href="/newsletters/2019/index.html">2019</a></li> -->
--

to

[xml]
--
  <li><a href="/newsletters/2019/index.html">2019</a></li>
--

For years after 2020 (for example 2021):

* Create a folder wrhs/assets/newsletters/2021/.

* Create a folder wrhs/content/newsletters/2021/.

* Edit wrhs/nbbuild.xml and add a new line to the "-post-jar" target following the example of the others.

* Edit file templates/menu.ftl and add a new line 

[xml]
--
  <li><a href="/newsletters/2019/index.html">2021</a></li>
--

in the "Newsletters" dropdown (~line 23).

* Add the newsletter as above (<<add-newsletter>>).

== Add an event

Create a pdf and a matching thumbnail (.png) and drop them in wrhs/assets/events/ in the same way as newletters (<<add-newsletter>>).

Files are presented in alphabetical order, so if you start the filename with the date, they will appear in date order.

== Change other content

Most of the content is generated from asciidoc (.adoc) files (http:///asciidoctor.org).

Edit the file in any text editor (NOT Word) following the existing example, then preview (<<sect-preview>>) and upload (<<sect-upload>>).

|===
|File | Generated page

|wrhs/content/join.adoc
|Join

|wrhs/content/links.adoc
|Links

|wrhs/content/tips.adoc
|Horticultural tips

|wrhs/content/about.adoc
|Society->About

|wrhs/content/society/workparties.adoc
|Society->Work parties

|wrhs/content/society/meetings.adoc
|Society->Meetings. See <<addmeeting>>.

|wrhs/content/society/contacts.adoc
|Society->Committee

|wrhs/content/tips/
|Not used (future)

|===

== Change the theme

Edit files in wrhs/assets/css/. 
You are on your own. (but needs work).

== Edit the format of Trading Post product listings

These are done in Java. 
See the Builder class in wrhs/src/.

== Edit the format of automatically indexed folders

Eg events, newsletters.

These are done in Java. 
See the CatalogueFolder class in wrhs/src/.

// end::body[]
