= Join us
Rocky Allen
2013-10-17
:jbake-type: page
:jbake-status: published

== JOIN NOW - GET MEMBERSHIP UNTIL 31st MARCH 2019 FOR £5.00

== MEMBERS BENEFITS

* Access to the Trading Post, which stocks a wide range of horticultural products,
tools, seeds, and WRHS grown plants, all at very competitive prices.
You don't need to buy much to recover the cost of your membership fee.

* Hire of gardening tools at very modest rates

* Use of the Internet Café at the Trading Post, offering

** Free Wi-Fi hotspot

** Free use of an iPad

** Free access to current gardening magazines

** Free use of library books on all aspects of gardening and allotment cultivation 

** Free gardening advice at the Trading Post during opening hours

* Free short horticultural talks, with question & answer sessions, at the Trading Post

* A free copy of the WRHS monthly newsletter delivered by email

* Access to social events, including coach trips, quiz/buffet nights, Summer Show

* The right to participate in running the Society

* The right to vote at the AGM

* The right to stand for election to the General Committee

* The right to sell home-grown plants at the Trading Post 

**The terms of the Society's trading licence prevent the Society from selling goods or services to the general public, so the benefits listed above are strictly exclusive to WRHS Members**

== ASSOCIATE MEMBERSHIP

Other members of the household living at the same address as a WRHS Member may become Associate Members without further payment, but have no voting rights

== GROUP MEMBERSHIP
At the discretion of the General Committee, local organisations (such as schools)
may obtain Group Membership. Enquiries should be made to the General Secretary

email: mailto:general_secretary@wrhs.org.uk[]


