:stylesheet: plain.css
= Which Fertiliser?
Rocky Allen
2013-10-17
:jbake-type: page
:jbake-status: published

The shelves in the Trading Post display a dazzling selection of food for our plants, but 
which do we need? 
A plant’s main foods are nitrogen, phosphorus and potassium, dissolved in water and taken up by roots. 
These are known to gardeners by the chemical symbols NPK. 
The packaging gives numbers for these that depict the proportions of minerals in the fertiliser. 
N:P:K might be 20:5:18. 
Why does this matter? 
Plants use these nutrients for different purposes: nitrogen encourages leaf growth, phosphorus feeds the 
flowers, and potassium improves the roots and fruits. 
During WWII, growing your own food was encouraged and a fertiliser called Growmore was produced. 
Growmore is a general purpose fertiliser with an N:P:K of 7:7:7. 
(Maxicrop Complete Garden feed is 5:5:5). 
It is essential to follow the dosage advice given by the manufacturers: overdosing can result in 
damaged plants.

In the early stage of growth, nitrogen and potassium are required to build a robust plant. 
Thus we choose a fertiliser with high N and K, but low P. 
(Vitax Q4+ Natural Organic is approx 5:3:8, to stimulate root growth. 
Phostrogen All Purpose is 14:10:27 is suitable for use once the young plants are established). 
To some extent we can control a plant’s development according to what we want. 
If we are growing root vegetables, such as carrots, we want big roots, so a fertiliser high in P and K is required 
(Vitax Q4 Premium Soluble Plant Food 7:4:30). 
A sprinkling of Epsom salts, (Potassium Sulphate or Sulphate of Potash) will boost the K, if using a balanced general purpose fertiliser. 
Alternatively, if we are growing leafy vegetables (brassicas), we need a lot of nitrogen most easily obtained with pelleted poultry manure. 
Small quantities of Ammonium sulphate can be used to boost N. (Sportsmaster Pro for grass is 14:0:5). 
If we add too much P and K, the plant will head for flower production and bolt. 
If it is flowers we are after, then we use the high N and K until we have strong plants, then reduce the N and increase the P, phosphorus. 
This applies, of course, if you want the flowers to produce fruit, but potassium is also required to maintain a strong root network to feed the plant, as well as to enhance the fruit. 
Tomatoes are rich in potassium, so Vitax LiquidTomato Feed is 4:0:9.5 or Maxicrop Organic Tomato Feed is 4:1:5, to be used once the fruit has set.
There are other minerals that plants require, but in much smaller quantities, called micronutrients: iron, calcium, copper, zinc, sulphur, manganese, etc. These quantities remain much the same regardless of the NPK ratio, but the absence of any of them weakens the plant. 
Such deficiencies can be diagnosed by yellowing of the leaves, and rectified quickly.
In nature, a plant takes up all these nutrients from the soil, and by shedding leaves, returns them to the soil. 
Organic gardeners can therefore make compost from plant material and apply that round the roots. 
Some components of compost can be varied by choosing different plant materials, especially seaweed. 
Nettles and comfrey can be rotted in water to apply round the plants. 
Additional nitrogen is usually obtained from fish, blood and bone compounds (3:9:3) and animal manure. 
All the nutrients have to be dissolved before the plants can absorb them, so they are generally supplied as compounds, such as nitrates, sulphates and phosphates.

Bibliography: Brian Capon, Botany for Gardeners, 1998, Batsford

