:jbake-type: page
:jbake-status: published
:stylesheet: ../css/material-green.css
= About WRHS
Rocky Allen
2013-10-17

The WRHS is a friendly club for amateur gardeners and allotment holders, run by volunteers for the benefit of its members.
Membership is open to all, not just Wyke Regis residents.
The Society currently has 537 members living in Weymouth, Chickerell, Portland, & Dorchester.

Membership costs just £5 per annum.
The membership year runs from 1st April, but new members who join between 1st January and 31st March get the those initial months free.
You can join the WRHS at the Trading Post in Rylands Lane, at any time during trading hours.

The Trading Post stocks a wide range of horticultural products for sale to WRHS Members at very competitive prices,
making it easy to recoup the cost of membership.

The Trading Post is currently opens on Wednesdays from 2pm to 6.30pm and on Saturdays from 9:30am to 12:30pm
Plants raised by the WRHS are very popular with members. 
Plants raised by members are also offered for sale.
The terms of the Society's trading licence allow the Society to sell goods and services to its members, but not to the general public.

The Trading Post hosts an Internet Cafe offering refreshments during trading hours.
A Wi-Fi hotspot, an iPad, a gardening library, and current gardening magazines are all available for use by members, free of charge.

Social events include coach trips, quiz nights, plant exchange days, and a Summer Show.
Group Membership is offered to local organisations such as schools.
Other members of the household living at the same address as a WRHS Member may become Associate Members without further payment.
The General Committee, elected by the Members at the annual General Meeting, is responsible for the day to day running of the Society.
The WRHS Constitution gives full details of WRHS Membership and all other matters relating to the Society.
 
Trading Post telephone: 01305 759668

Enquiries by email may be made to: mailto:generalsecretary@wrhs.org.uk 
